export default {
  zeroxEthereum: 'https://api.0x.org',
  zeroxBsc: 'https://bsc.api.0x.org',
  zeroxPolygon: 'https://polygon.api.0x.org',
  oneinch: 'https://api.1inch.exchange/v3.0',
  limitOrders: 'https://limit-orders.1inch.exchange/v1.0',
  horizon: 'https://horizon.stellar.org',
  blocktrail: 'https://api.blocktrail.com/v1/BTC',
  bitpay: [
  'https://api.bitcore.io/api/BTC/mainnet',
    //'https://insight.bitpay.com/api',
    //'https://invoices.swaponline.site/proxybitpay',
  ],
  ghostscan: 'https://ghostscan.io/ghost-insight-api',
  nextscan: 'https://explore.next.exchange/#',
  nextExplorer: 'https://next.swaponline.io/mainnet',
  nextExplorerCustom: 'https://next.swaponline.io/mainnet',
  blockcypher: 'https://api.blockcypher.com/v1/btc/main',
  etherscan: 'https://api.etherscan.io/api',
  etherscanInvoices: 'https://invoices.swaponline.site/proxyetherscan',
  etherscan_ApiKey: 'BEAQZTKC5A3VJ1ZYX657NK6APBSDCE6ZSN',
  bscscan: 'https://api.bscscan.com/api',
  bscscan_ApiKey: '67WDAPT6AQSN5WK4ESSRIDS2AG81SY7H1N',
  maticscan: 'https://api.polygonscan.com/api',
  polygon_ApiKey: '1BPUW25YSBJTM69EBCZW8VZYQI4HUQ1ZAC',
  faucet: 'https://faucet.swaponline.site/mainnet/',
  btc2FAProtected: 'https://2fa.swaponline.site',
  btcPin: 'https://2fapin.swaponline.site',
  invoiceApi: 'https://invoices.swaponline.site',
  multisig: 'https://multisig.swaponline.site',
  txinfo: 'https://txinfo.swaponline.site',
  noxon: 'https://noxon.wpmix.net',
}
